<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_checkbox</name>
   <tag></tag>
   <elementGuidId>e40320b8-6ffb-4cd7-956d-40ac6223c55d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.\!h-auto.text-center .peer.data-\[state\=indeterminate\]\:bg-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' !h-auto ') and contains(concat(' ', normalize-space(@class), ' '), ' text-center ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ') and (contains(concat(' ', normalize-space(@class), ' '), ' data-[state=indeterminate]:bg-primary '))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4a132ae-3dc2-4c8d-ab93-556fe857caed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6c0089c-e79b-43d4-9832-c1775ea894d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6f38be30-6c23-4bcb-9961-f1e7a21284d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2cbef79e-825c-466e-989e-c231808391f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>9efd8d4d-5a75-4b19-b03d-195b91c8fe02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>77012ce5-40a3-4a00-9dff-590707ba6d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e3559c9f-4636-4c6d-9416-6117b44ffc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer peer border-input data-[state=unchecked]:bg-white data-[state=checked]:bg-primary data-[state=indeterminate]:bg-primary data-[state=checked]:text-primary-foreground data-[state=checked]:border-primary data-[state=indeterminate]:border-primary focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive size-4 shrink-0 rounded-[4px] border shadow-xs transition-shadow outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50</value>
      <webElementGuid>bc4803dd-1d59-4094-8141-3f0abc6c5f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-60472cc7cb49e6a3dd4d1f6c0c190e82</value>
      <webElementGuid>b5b30a2c-97dd-4fdc-bba4-4f601132d388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' !h-auto ') and contains(concat(' ', normalize-space(@class), ' '), ' text-center ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ') and (contains(concat(' ', normalize-space(@class), ' '), ' data-[state=indeterminate]:bg-primary '))]</value>
      <webElementGuid>2148969c-76c6-4e1b-ab43-bbc2e12d3c76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' !h-auto ') and contains(concat(' ', normalize-space(@class), ' '), ' text-center ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ') and (contains(concat(' ', normalize-space(@class), ' '), ' data-[state=indeterminate]:bg-primary '))]</value>
      <webElementGuid>72528110-93e9-4521-a39d-390a95de40d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>34a40d94-cb4d-48e9-9e84-3c5f85510ca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
