<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_data-stateopen_animate-in data-stateclo</name>
   <tag></tag>
   <elementGuidId>9e365578-b2b3-4168-9137-0ab189b34d5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-slot=&quot;dialog-overlay&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-slot = 'dialog-overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cbcb25ea-1e09-4bec-8ac4-bf3a60540721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>c1329f14-8841-4a68-8ca0-24b70a87e6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>dialog-overlay</value>
      <webElementGuid>3e379f85-6ec3-495d-add8-946cd1bc80fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 fixed inset-0 z-50 bg-black/80</value>
      <webElementGuid>2da29566-743b-4868-9eba-572ec37bc197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>05eb1e42-85f9-4e55-ac02-fca085c6efb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76cb14c1-f59b-4201-a35a-272081585cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d1e895a874754b53c11784f145f71b93</value>
      <webElementGuid>66f06a63-3522-4435-a3b0-f6aaad894e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-slot = 'dialog-overlay']</value>
      <webElementGuid>8d1a3737-a62d-4e70-ba8d-ee3cbf39a93d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-slot = 'dialog-overlay']</value>
      <webElementGuid>0d2be0ba-be4e-4eaf-88f6-a399149d5f00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
