<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__storerkey_search</name>
   <tag></tag>
   <elementGuidId>cdca6a23-2742-4f83-87ee-6af7bea434f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.w-full.rounded-t-md.bg-background.z-10.outline-none.ring-0.border-b.border-zinc-200.px-3.py-2.shadow-none.text-zinc-600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Search...']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79284364-0bc1-4d77-b5e4-936873c87aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full rounded-t-md bg-background z-10 outline-none ring-0 border-b border-zinc-200 px-3 py-2 shadow-none text-zinc-600</value>
      <webElementGuid>ad56fe8e-c9fa-46c4-8052-102cb2ee75a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>a7d3bb22-cb64-408d-8839-49071da601c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>page.consignment-form-v2.po_data.0.storerkey.components.select-input.search-input</value>
      <webElementGuid>81ccba58-e2ac-453f-8a69-32f2dd3e11dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_32_&quot;)/input[@class=&quot;w-full rounded-t-md bg-background z-10 outline-none ring-0 border-b border-zinc-200 px-3 py-2 shadow-none text-zinc-600&quot;]</value>
      <webElementGuid>fdb56f31-9dfc-4b59-949f-8b51ae87de5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>311b66f4-b46a-46a7-924a-68bbfa4ca4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_32_']/input</value>
      <webElementGuid>dbe88c48-052d-4d57-897b-740f19415d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>13c8a184-cfe2-4e22-9da9-235773942bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search...']</value>
      <webElementGuid>eb88f7f0-cf51-4e40-a134-c9ac50d3bb57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
