<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FF</name>
   <tag></tag>
   <elementGuidId>d2f78022-312b-4cea-bab8-cc85e15fd2f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id = 'select-input' and @type = 'button' and (text() = 'ARAMEX LOGISTICS (EXPRESS)' or . = 'ARAMEX LOGISTICS (EXPRESS)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1248030-aa00-4b10-b9fc-746f98d1cd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>popover-trigger</value>
      <webElementGuid>35dd2190-6e3d-46c8-ba2e-e1d261d100cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center gap-2 whitespace-nowrap transition-[color,box-shadow] cursor-pointer disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg]:shrink-0 ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 focus-visible:ring-4 focus-visible:outline-1 aria-invalid:focus-visible:ring-0 border shadow-xs hover:text-accent-foreground py-2 has-[>svg]:px-3 !h-[46px] w-full justify-between bg-background font-medium hover:bg-background my-0 font-red-display h-[46px] rounded-lg border-[#E5E5E5] px-[17px] text-[14px] leading-5 text-[#333]</value>
      <webElementGuid>53a98140-5385-44e5-b62a-50910a5f2a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>f87f8215-388a-4676-8b89-d57e726edf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>29287728-bd17-4f28-8ea9-d44fb07f6b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d4a34881-e55c-4419-bfaa-c4934bf85ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>components.select-input.trigger</value>
      <webElementGuid>e5e9ea55-eb12-44db-b93a-17d4964d86b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>584b2b43-3a08-4243-9f63-9a1b7ae08785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>9d73dc84-bf25-40d2-ab6a-1bc785404bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_3s_</value>
      <webElementGuid>48b65b43-b356-4fa3-9472-59f7f94abbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>616fac86-2f60-4153-893a-d03bd799c2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARAMEX LOGISTICS (EXPRESS)</value>
      <webElementGuid>c5ba7835-478b-4e73-9e98-a699f8f9ad34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_3r_&quot;)/div[@class=&quot;border-t border-[#EBEBEB] px-4 pb-4 pt-[5px]&quot;]/div[@class=&quot;flex flex-col gap-4 pt-3&quot;]/div[@class=&quot;grid gap-4 grid-cols-1 sm:grid-cols-2&quot;]/div[@class=&quot;flex flex-col gap-[6px]&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;rounded-sm&quot;]/button[@id=&quot;select-input&quot;]</value>
      <webElementGuid>c68f9e2d-29e7-4aa8-9835-2c056623579c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='select-input']</value>
      <webElementGuid>e5c6b705-3ca2-48d0-ba4b-6fdc4da6ff8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_3r_']/div/div/div/div/div/div/button</value>
      <webElementGuid>0f4e82df-aefa-4d46-a986-f1edf0946814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::button[1]</value>
      <webElementGuid>357b21c0-85c9-46ed-8dbe-c8ab79031e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div/div/button</value>
      <webElementGuid>e0d50119-89ce-46ea-be96-a9e14ef57ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'select-input' and @type = 'button' and (text() = 'ARAMEX LOGISTICS (EXPRESS)' or . = 'ARAMEX LOGISTICS (EXPRESS)')]</value>
      <webElementGuid>ef51f38e-8551-4c62-844c-6a5637c26984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
