<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select an option</name>
   <tag></tag>
   <elementGuidId>3d6ffa55-6063-4c57-b8ab-f2d0c1595781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mot']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mot</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a3342b3-6e23-4564-aa92-8a43bb614977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>popover-trigger</value>
      <webElementGuid>f086df62-2844-46d4-9167-e6172ebb5e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center gap-2 whitespace-nowrap transition-[color,box-shadow] cursor-pointer disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg]:shrink-0 ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 focus-visible:ring-4 focus-visible:outline-1 aria-invalid:focus-visible:ring-0 border shadow-xs hover:text-accent-foreground has-[>svg]:px-3 rounded-lg w-full justify-between bg-background font-normal text-active text-lg hover:bg-background my-0 px-4 py-3 min-h-[46px] h-auto border-destructive</value>
      <webElementGuid>f47079b5-1461-465d-9a76-13f0f373abec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>page.freight-forwarder-partner-form.mot.components.multiple-select-input.component.multi-select.trigger</value>
      <webElementGuid>64cb3807-deb6-4573-9efb-7c45496f2514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mot</value>
      <webElementGuid>bc34f681-aace-41b6-94d9-0d3634abd4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c03a21e-e687-4fd7-922b-968baeeaff93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>48a8f7d2-2b65-4232-8589-bc23ee157f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e800877b-cb4d-4de4-954b-021327b5f59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_35_</value>
      <webElementGuid>e41cfc37-ab13-4dd0-a8f8-e911d90ed310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>b8027cab-4158-4267-8b8e-76127386f0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an option...</value>
      <webElementGuid>db325e09-da2f-4a46-a594-9dbed70de411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mot&quot;)</value>
      <webElementGuid>38baa486-8e05-4b79-bd50-32abf2e8069e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mot']</value>
      <webElementGuid>5978ac95-662d-4b3c-a90e-ad268ceb0bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/section/main/div[2]/section/div[2]/div/div[2]/div/button</value>
      <webElementGuid>36c57e1c-e3c5-4ddb-9207-0106d51fc120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::button[1]</value>
      <webElementGuid>e37a2938-3709-4023-9b3e-40af3c23257a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select at least one option'])[1]/preceding::button[1]</value>
      <webElementGuid>cd1b258f-dd41-4fe5-bde4-ca3c0c24ef85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button</value>
      <webElementGuid>2f5977f6-fa9c-4b1f-8cb7-14a08cc659a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'mot' and @type = 'button' and (text() = 'Select an option...' or . = 'Select an option...')]</value>
      <webElementGuid>6b05e7a9-e62f-408d-b325-db4a3986d854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
