<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3toneSLB_US_LAND</name>
   <tag></tag>
   <elementGuidId>d2abbff3-2727-4a60-b9be-8864b4ef25de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mot']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-wrap.items-center.gap-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>05f3733e-bc6d-4b68-b2ea-96e24d6091a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-wrap items-center gap-1</value>
      <webElementGuid>51a961e4-5da7-4264-8fa9-1e813fc8604f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3toneSLB_US_LAND</value>
      <webElementGuid>4beba809-9a7f-44ae-a168-8fa849a53ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mot&quot;)/div[@class=&quot;flex justify-between items-center w-full&quot;]/div[@class=&quot;flex flex-wrap items-center gap-1&quot;]</value>
      <webElementGuid>bf014553-d5cf-4119-820c-78454f7f1ea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='mot']/div/div</value>
      <webElementGuid>38f61c5c-86b7-4f7b-aeca-938e212ba263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[3]</value>
      <webElementGuid>bc939ef1-3713-481d-a5f1-bc9d384af596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div</value>
      <webElementGuid>73cb26ff-cce3-417f-9ffe-6dfe6651dc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '3toneSLB_US_LAND' or . = '3toneSLB_US_LAND')]</value>
      <webElementGuid>8238b92f-fd62-48dc-b6d1-ab5c6fb47a57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
