<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_HubDropdown</name>
   <tag></tag>
   <elementGuidId>2c1c201b-2c60-48f1-b5ef-fd7d937c5901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hubs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hubs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>107a917a-ef62-404e-bb9c-e6e2b158ffff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>popover-trigger</value>
      <webElementGuid>41c6be4d-7fe3-4ee9-989d-b63456e5df25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center gap-2 whitespace-nowrap transition-[color,box-shadow] cursor-pointer disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg]:shrink-0 ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 focus-visible:ring-4 focus-visible:outline-1 aria-invalid:focus-visible:ring-0 border shadow-xs hover:text-accent-foreground has-[>svg]:px-3 rounded-lg w-full justify-between bg-background font-normal text-active text-lg hover:bg-background my-0 px-4 py-3 min-h-[46px] h-auto border-destructive</value>
      <webElementGuid>ed806d11-7126-4f2c-af2a-4cb637426d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>page.operation-user-form.hubs.components.multiple-select-input.component.multi-select.trigger</value>
      <webElementGuid>1ea4ff8d-6ed0-4f64-941f-e78a2cea4d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hubs</value>
      <webElementGuid>06ea6f07-7da2-4832-8677-96a3a3af42e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e62bd973-defa-4f0f-8729-62b57894ce6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>9b0a1af4-67c8-4ee5-b383-ae9ac93570fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2f28b911-ba20-4886-9d5d-df76f1e72868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_1p_</value>
      <webElementGuid>1f53377b-af0a-4227-a254-ace87aa20e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>c6b40012-4d5e-4baf-bdae-cc32cf7a4b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select options</value>
      <webElementGuid>346f06c7-1877-4622-a776-b3f2c7e9f5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hubs&quot;)</value>
      <webElementGuid>a505fae6-41c5-400c-8e1c-9ee371d269ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='hubs']</value>
      <webElementGuid>2968bd79-166d-4e87-a784-bbc85841ccf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/section/main/div[2]/div[2]/div/div[7]/div/button</value>
      <webElementGuid>573b3d9a-b1d1-4b60-8015-00a862ae9e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::button[1]</value>
      <webElementGuid>a249be3c-837a-4bba-88aa-361532b0cdc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select at least one'])[1]/preceding::button[1]</value>
      <webElementGuid>b16633eb-d329-4046-844a-79b678e7894e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button</value>
      <webElementGuid>4ec0032e-f9b3-4a18-8202-04b5c42b8219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'hubs' and @type = 'button' and (text() = 'Select options' or . = 'Select options')]</value>
      <webElementGuid>dff5b3bd-0548-4ad0-b092-a5ee0b1bed27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
