<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select hub</name>
   <tag></tag>
   <elementGuidId>c7a18ce5-ec74-4f54-86d9-86de5a5c11fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.justify-between.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hubs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62845cda-e674-4903-ae16-4223026aa824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between w-full</value>
      <webElementGuid>8872b2c6-7ed3-4ec2-b006-0037eedf0937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select options</value>
      <webElementGuid>cb5543aa-4049-458d-8f1a-97fd0aadd20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hubs&quot;)/div[@class=&quot;flex items-center justify-between w-full&quot;]</value>
      <webElementGuid>611e859f-91b0-4700-b2ae-0a83ba9e1c99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='hubs']/div</value>
      <webElementGuid>de2028d6-de8f-4a0f-a8b0-f267dfd4cf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected Hub'])[1]/following::div[2]</value>
      <webElementGuid>5d550a7a-fb3e-4008-a73b-077fe3287db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::div[4]</value>
      <webElementGuid>ad7c4f97-f410-4734-a127-8feb397b17b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected Storer Key'])[1]/preceding::div[1]</value>
      <webElementGuid>3a24fa14-f393-4639-bb28-068079b987f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>aa3ebdd0-5c0e-47fe-8508-fa85dcd80acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select options' or . = 'Select options')]</value>
      <webElementGuid>de94ddf3-3b03-47f1-884d-4432c0379cc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
