<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_1</name>
   <tag></tag>
   <elementGuidId>4f3dc089-b549-424c-913d-58af76c81702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.rounded-sm.shadow-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-sm ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>deb9154b-a74d-4393-b98d-fa3255a260cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de0a6f7f-96c3-4c4f-8375-4423dd315d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>justify-center whitespace-nowrap text-sm font-medium transition-[color,box-shadow] cursor-pointer disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg]:shrink-0 ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 focus-visible:ring-4 focus-visible:outline-1 aria-invalid:focus-visible:ring-0 shadow-sm rounded-sm h-9 px-4 py-2 has-[>svg]:px-3 flex items-center gap-2 bg-[#DC291E] text-white hover:bg-[#b81f16]</value>
      <webElementGuid>6c57c025-5f39-4d27-930b-b527172b7878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>43e9a2fa-f59f-48fc-8432-538a64f8c7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9e7f6938a52cbe015315a8ecab53681d</value>
      <webElementGuid>ca335cd9-642d-4582-845d-a291c6b2be00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-sm ')]</value>
      <webElementGuid>59af2d0d-d703-4d91-86ec-9ce67ac8f933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-sm ')]</value>
      <webElementGuid>58da8d6f-a378-4db1-8e32-bf4f55ff3971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>5a0ccb8a-7454-4f53-9b98-5621fcb4d5d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
