<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Package Type</name>
   <tag></tag>
   <elementGuidId>5a82cf9d-c5af-4e66-ad94-326ba97b1124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#package_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'package_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb41e7fd-3915-4b9a-ab9d-dff4778ff9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>popover-trigger</value>
      <webElementGuid>28964e79-77ed-4435-950c-d35334ec7df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center gap-2 whitespace-nowrap transition-[color,box-shadow] cursor-pointer disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg]:shrink-0 ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 focus-visible:ring-4 focus-visible:outline-1 aria-invalid:focus-visible:ring-0 border border-input shadow-xs hover:text-accent-foreground py-2 has-[>svg]:px-3 rounded-lg !h-[46px] w-full justify-between bg-background font-medium text-md text-text-primary hover:bg-background my-0 font-red-display px-3 h-[40px]</value>
      <webElementGuid>97e496e2-1404-48d2-91a1-b2f38c4c7a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>package_type</value>
      <webElementGuid>08b221af-16e2-4f94-9ebd-ed9fe4db0e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>4a7115d7-8181-41b8-bb22-cd34fcdae3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac422b4c-a9cf-43a6-b0bc-cc827e233f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>package_type</value>
      <webElementGuid>b1e42855-57ad-42f4-90e2-7cfcf60dda1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>page.consignment-package-form.package_type.components.select-input.trigger</value>
      <webElementGuid>68466bba-653b-4524-9b01-95b9c00d1366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a67f5f08-efd1-45ca-8266-9c43cac86d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>8cfefa2b-1ae6-4860-8c0c-c937d44feb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_24_</value>
      <webElementGuid>f9476cbf-c77f-4ba4-a71f-1a464554ca6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>d2c82c48-2015-4baa-94ad-7972723c41e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3f404794139b0b12002a54c175d0a603</value>
      <webElementGuid>2379a502-f428-4427-87bb-4bda2a980aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'package_type']</value>
      <webElementGuid>48f230e6-3616-4bce-b881-97aa3f898022</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'package_type']</value>
      <webElementGuid>54192294-b1c9-4603-bee1-b0acf11633ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'package_type' and @name = 'package_type' and @type = 'button']</value>
      <webElementGuid>3a569c47-d5f4-43f8-989f-f91dfd78838a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
