<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_switch</name>
   <tag></tag>
   <elementGuidId>09499553-3a8f-4345-8676-e0c39b366f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-child(3) .peer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'td') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93404f38-618e-49e8-8308-3b048e2a4049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1b6c608-17b3-4a96-b96c-5b9619bc9b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>d9b8b98c-7bd0-48de-9e1a-b33de3b8c974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd2565d6-d2f7-4c41-bcae-72eb0ced3134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>53811bd7-3cbb-4bc4-8027-50e5c1b47e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>289158b6-cc8b-4791-bc0a-2fbd075eaa24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>dfa6ef8a-0ad3-4ceb-b04f-6809bbb93283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peer data-[state=checked]:bg-primary focus-visible:border-ring focus-visible:ring-ring/50 inline-flex shrink-0 items-center rounded-full border-transparent shadow-xs transition-all outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 h-[19px] w-[34px] border-0 bg-[#F2F2F2] data-[state=unchecked]:bg-[#F2F2F2] **:data-[slot=switch-thumb]:size-[17px] **:data-[slot=switch-thumb]:shadow-[0.6px_0.6px_1.2px_rgba(0,0,0,0.15)] [&amp;_[data-slot=switch-thumb][data-state=checked]]:translate-x-[15px] cursor-pointer false</value>
      <webElementGuid>8ad84f96-7ea7-4cd5-b010-6bcfb02d2e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2c6da7b2d11d529ca5b11bc5045b9541</value>
      <webElementGuid>130cc09c-a417-4904-a777-48f4d14021f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'td') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ')]</value>
      <webElementGuid>e65a9612-bb1b-4bbc-80c8-bee4625062e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'td') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ')]</value>
      <webElementGuid>05a17096-50c1-44f8-9a59-e77aa060f96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>d1a884c5-a860-428c-a8ed-2b2a00005b61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
