<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_checkbox_1</name>
   <tag></tag>
   <elementGuidId>4a9dc46a-7c52-47f6-b15c-d49c242c731e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.text-center .peer.data-\[state\=indeterminate\]\:bg-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-center ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ') and (contains(concat(' ', normalize-space(@class), ' '), ' data-[state=indeterminate]:bg-primary '))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b72fa78a-4ee4-4853-bb74-7c5bab798088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7641ddc-f8b5-4929-ae50-106645f1abd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b6209a12-42fe-4955-9e12-85558184f69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2fef1930-e8ea-4fc9-8f27-f471fc30b9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>5629c581-5ae8-448a-b877-b2170d719e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6f86284b-2cce-4390-9379-29ac6408b017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c064d49c-7acf-4235-bfff-557d7c72b0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer peer border-input data-[state=unchecked]:bg-white data-[state=checked]:bg-primary data-[state=indeterminate]:bg-primary data-[state=checked]:text-primary-foreground data-[state=checked]:border-primary data-[state=indeterminate]:border-primary focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive size-4 shrink-0 rounded-[4px] border shadow-xs transition-shadow outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50</value>
      <webElementGuid>564a0ef6-3bf5-414d-b984-35132b2cc019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c636eeb51785d286f4789288c92d807d</value>
      <webElementGuid>aaeb7f0c-861e-4e8e-a036-e2867b47c717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-center ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ') and (contains(concat(' ', normalize-space(@class), ' '), ' data-[state=indeterminate]:bg-primary '))]</value>
      <webElementGuid>59aa04a6-37df-422c-9094-23adb9ab5e83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-center ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ') and (contains(concat(' ', normalize-space(@class), ' '), ' data-[state=indeterminate]:bg-primary '))]</value>
      <webElementGuid>7e616314-3a31-4417-801b-cc7361972016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>68ea0593-4cd5-4970-aafb-625fa4fc05f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
