<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Details</name>
   <tag></tag>
   <elementGuidId>3c7ac9c0-9f28-40e7-83df-2256557bfa8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-slot=&quot;drawer-trigger&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-slot = 'drawer-trigger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7968a1e-2b98-4b3c-b331-64bea15748fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>drawer-trigger</value>
      <webElementGuid>e235617c-d035-4409-9f77-c5547ba5874b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md transition-[color,box-shadow] cursor-pointer disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg]:shrink-0 ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 focus-visible:ring-4 focus-visible:outline-1 aria-invalid:focus-visible:ring-0 hover:text-accent-foreground has-[>svg]:px-3 h-auto w-auto p-0 text-[13px] font-medium leading-[19.5px] text-[#0E5FB8] hover:bg-transparent hover:underline underline-offset-4</value>
      <webElementGuid>c88be86d-6663-4a0c-80d7-39ae17591af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5d1c62f-e7c1-45bd-b1ca-80e246370ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>f2c0b215-8bbe-431f-bad4-a81319bd5be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9763437b-2bf8-4b51-9670-cd3d424055e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_1p_</value>
      <webElementGuid>c1d5e8f5-6cb4-4eca-93ca-1c6da7b789cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>bc2881ce-fddb-4868-8561-e36616bdfb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Details</value>
      <webElementGuid>dace7a78-f7dd-4d7b-a27c-4a2b43be15f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3f5db618a8a8a01143601b53dc386308</value>
      <webElementGuid>144bc641-eec6-4906-ab35-295480351892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-slot = 'drawer-trigger']</value>
      <webElementGuid>9f51f758-0688-4773-985d-8edc596177ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-slot = 'drawer-trigger']</value>
      <webElementGuid>fa7f4336-62b1-47ce-a782-deb92334ae21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add Details' or . = 'Add Details')]</value>
      <webElementGuid>cfb98b91-1880-4d2f-8d51-b3378314ce69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
