<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_switch_1</name>
   <tag></tag>
   <elementGuidId>3f651674-5a27-45c6-821a-2835afc22044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.peer.shadow-xs.rounded-full.border-transparent.transition-all[data-slot=&quot;switch&quot;][value=&quot;on&quot;][role=&quot;switch&quot;][data-state=&quot;unchecked&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xs ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' border-transparent ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-all ') and (@data-slot = 'switch') and (@value = 'on') and (@role = 'switch') and (@data-state = 'unchecked')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1d575d2-a112-4b23-a03d-04cec8a4ff66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2222fc8-8b67-41a6-8189-61898e0697a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>c5576d0f-6f1c-4c4a-9a8c-175befce9918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>14224203-4c8c-4f30-b0e3-81345634fb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>e5ce1c4e-08bc-4538-8b53-7eeea724ae8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3b16647e-e886-4dca-a8e4-df6c16753f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>6d87ed5f-dd76-4a00-b0e5-ad5e23f40512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peer data-[state=checked]:bg-primary focus-visible:border-ring focus-visible:ring-ring/50 inline-flex shrink-0 items-center rounded-full border-transparent shadow-xs transition-all outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 h-[19px] w-[34px] border-0 bg-[#F2F2F2] data-[state=unchecked]:bg-[#F2F2F2] **:data-[slot=switch-thumb]:size-[17px] **:data-[slot=switch-thumb]:shadow-[0.6px_0.6px_1.2px_rgba(0,0,0,0.15)] [&amp;_[data-slot=switch-thumb][data-state=checked]]:translate-x-[15px] cursor-pointer false</value>
      <webElementGuid>18d71346-11fe-4d36-a907-ea328cc13e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ec10d3980f87aff5b765553a2e7ddaaa</value>
      <webElementGuid>69e2b62a-5585-4e55-ad47-944aec9b13ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xs ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' border-transparent ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-all ') and (@data-slot = 'switch') and (@value = 'on') and (@role = 'switch') and (@data-state = 'unchecked')]</value>
      <webElementGuid>c0b31e41-02c6-4459-837a-30deae69ed8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xs ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' border-transparent ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-all ') and (@data-slot = 'switch') and (@value = 'on') and (@role = 'switch') and (@data-state = 'unchecked')]</value>
      <webElementGuid>e4c421ee-56f7-4b54-8bd7-f9057bbc97ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>2888dc33-425f-47f6-8c4e-e0538399a4db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
