<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__r_8c</name>
   <tag></tag>
   <elementGuidId>87b2189c-8d04-4556-ba78-f3ae4169fb81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-ref=&quot;country_of_origin\.components\.select-input\.option\.AF\ \(Afghanistan\)&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-ref = 'country_of_origin.components.select-input.option.AF (Afghanistan)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ae74a22-b7b9-42cd-8a3a-a5c6d41ad8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>command-item</value>
      <webElementGuid>7be2f87b-b9f5-4e6b-acc9-fdd501adfb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground [&amp;_svg:not([class*='text-'])]:text-muted-foreground relative flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 cursor-pointer !hover:bg-background hover:font-semibold mb-1</value>
      <webElementGuid>2dce3ec3-c5f9-4d1a-bec1-ba0f10c83c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>country_of_origin.components.select-input.option.AF (Afghanistan)</value>
      <webElementGuid>1ed4766d-cb57-49a4-92ad-dd4aead57d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_r_5m_</value>
      <webElementGuid>f09d98eb-6307-477c-b52b-ce4245451a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ebe7a142-51a0-49cf-a8bf-7748d3a78902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e3e7c563-d0ed-4734-a631-02902702e1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c07ba0d1-fa6d-4f63-adfe-2a81b3727535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8f48489-39ae-4ca6-87cf-076241e8a631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c2bf02af-5a14-4354-8dd9-f4ef68a535c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;06834408-156b-4c52-b705-68b45e3850c6&quot;,&quot;value&quot;:&quot;AF&quot;,&quot;label&quot;:&quot;AF (Afghanistan)&quot;}</value>
      <webElementGuid>5f2ef96e-aa7a-4739-b032-9cc0402aa8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AF (Afghanistan)</value>
      <webElementGuid>2bf9dc8f-1e6a-4077-86f3-f1ad106e47af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-13ca7ce859389e83d3867d31adb004fe</value>
      <webElementGuid>2d18f4f5-d89e-435d-afe3-ce7e59b4da2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-ref = 'country_of_origin.components.select-input.option.AF (Afghanistan)']</value>
      <webElementGuid>a2170f6b-4e73-47a1-bfd8-c12a008a50c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-ref = 'country_of_origin.components.select-input.option.AF (Afghanistan)']</value>
      <webElementGuid>a2706f95-b936-4c67-9ddf-d2a2d87bc7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_r_5m_' and (text() = 'AF (Afghanistan)' or . = 'AF (Afghanistan)')]</value>
      <webElementGuid>ca5b180f-5c2c-47ed-ac2a-6617c7a5a61c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
