<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Others</name>
   <tag></tag>
   <elementGuidId>f403e450-cbee-4543-9428-6d63b6cf3d27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-lg ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-white ') and (position() = 5)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.rounded-lg.bg-white:nth-child(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1a4b443-7cbf-409c-aebc-c72a21b27e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd6a6a2f-da74-4219-9e38-fdeff997480c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-[84px] min-w-0 flex-col gap-0.5 rounded-lg border px-3 py-2.5 text-left transition-colors border-[#E5E5E5] bg-white hover:border-[#DC291E]/40</value>
      <webElementGuid>f1a30426-d50d-4f89-b804-ae7fd35d4ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OthersGeneral issues without a linked reference</value>
      <webElementGuid>c77a5ae5-9430-4320-822b-a72ded4801da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cb8df8723c12ed828f04a99f7cebfbe1</value>
      <webElementGuid>9af02835-dccb-4b01-a7f9-1d7d6fb91b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-lg ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-white ') and (position() = 5)]</value>
      <webElementGuid>1f865b8f-f18c-4cc7-86ae-62fb8d959fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-lg ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-white ') and (position() = 5)]</value>
      <webElementGuid>6eb70c98-019b-415a-bac9-f7b1b0d576ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'OthersGeneral issues without a linked reference' or . = 'OthersGeneral issues without a linked reference')]</value>
      <webElementGuid>66768f3e-9e1e-49d3-8e23-7606087d5cc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
