<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PackageLabels</name>
   <tag></tag>
   <elementGuidId>c728d3dc-7e0e-4458-993f-93344189d238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-lg ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-white ') and (position() = 4)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.rounded-lg.bg-white:nth-child(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1270fe7-3a46-4824-84a3-6fba22ef55bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01978494-e09a-4b3f-a4d0-75e1fe2a8bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-[84px] min-w-0 flex-col gap-0.5 rounded-lg border px-3 py-2.5 text-left transition-colors border-[#E5E5E5] bg-white hover:border-[#DC291E]/40</value>
      <webElementGuid>43dfd325-7458-4895-880b-6c4262d82be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PackageLabels, packaging, contamination</value>
      <webElementGuid>cce48d41-c0ac-45fa-8ca3-56e8da18ea73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e61ef48aeb4115c68a5c4cfaafc9056e</value>
      <webElementGuid>b40389f3-fca0-4181-b0cb-de2427c0acd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-lg ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-white ') and (position() = 4)]</value>
      <webElementGuid>c90e5863-7411-4b89-934c-2f83eed0ac7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-lg ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-white ') and (position() = 4)]</value>
      <webElementGuid>68920a2f-2edb-43f9-b438-df12299f97d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'PackageLabels, packaging, contamination' or . = 'PackageLabels, packaging, contamination')]</value>
      <webElementGuid>c2035445-ba61-42a8-84e5-a74ce5e341a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
