<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drop photos or browse</name>
   <tag></tag>
   <elementGuidId>b485a156-d433-4df0-a63a-6d633508b017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' border-[#CCC] ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.rounded-sm.border-\[\#CCC\]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b972e77a-7983-4ffc-b9c3-adfb46dc31aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>87928315-790f-45e6-b256-1af348324306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ea350ec2-e1af-440d-93d3-292be038c79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2.5 py-1 drop-zone flex min-h-[90px] cursor-pointer flex-col items-center justify-center gap-1 border border-dashed mt-2 rounded-sm border-[#CCC] bg-white</value>
      <webElementGuid>932ca06e-2d5a-4400-8a8a-2a66644a576b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drop photos or browse </value>
      <webElementGuid>0bb03264-b5c7-4d6a-98dc-1f8b7afa196e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9455ff2e7d091284020d8d3fe2673f33</value>
      <webElementGuid>e4442c49-65d4-4324-9935-26e370d530e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' border-[#CCC] ')]</value>
      <webElementGuid>36c83269-ac7a-47f1-89d9-b5af9e0082c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' border-[#CCC] ')]</value>
      <webElementGuid>dda71166-154c-49dc-b71e-ff6a9957866d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drop photos or browse ' or . = 'Drop photos or browse ')]</value>
      <webElementGuid>1e982f14-44be-4039-86fb-5711a6142324</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
