<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_data-stateopen_animate-in data-stateclo</name>
   <tag></tag>
   <elementGuidId>fb373099-1284-4b28-94f7-e1eba4ebb33e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-slot = 'sheet-overlay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-slot=&quot;sheet-overlay&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43e00fa3-6f4c-4863-acef-49819e1c3c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>1814de18-b771-4d82-be3c-ac985800b25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>sheet-overlay</value>
      <webElementGuid>e06dd05c-97dd-4a2a-b9a1-1bf1297fa30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 fixed inset-0 z-50 bg-[rgba(51,51,51,0.21)]</value>
      <webElementGuid>5b0dfa1b-45a3-40bb-8146-850190641e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04c4ddcb-1054-4f6e-881f-cb0fc113ad26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c5b9462-32fd-4963-b808-6250dc63db20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-50cb1b290674d68f1961c79863a26e9c</value>
      <webElementGuid>f2fb832d-16e6-409b-a418-baf8208b036e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-slot = 'sheet-overlay']</value>
      <webElementGuid>df48003e-2f87-4210-bef4-4ab264d555df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-slot = 'sheet-overlay']</value>
      <webElementGuid>895c5a27-9708-4d4a-8fa1-263020a4be36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
