<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Remarks</name>
   <tag></tag>
   <elementGuidId>b685d9ad-85ad-4402-ae02-d1712acfff2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'remarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;remarks&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8a51c744-5ae5-403a-bab1-927ffb363336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a261f863-14d4-4937-b7ca-b7fb8c01cbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive flex field-sizing-content w-full border bg-transparent px-3 py-2 shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm min-h-[98px] resize-y rounded-lg border-[#CCC] text-[14px] leading-5 placeholder:text-[rgba(51,51,51,0.5)]</value>
      <webElementGuid>52e91afd-6e1f-4be0-9cd6-ce7a743dbbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>e7bb6cb5-d817-4426-a937-a55988d1024f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Describe the non-conformance, what was expected vs. observed, and any actions already taken…</value>
      <webElementGuid>3edaa245-74f2-4255-97c0-0027e66b43d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_r_3u_-form-item</value>
      <webElementGuid>8130e969-1553-4a62-8204-4931be4a88fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>_r_3u_-form-item-description</value>
      <webElementGuid>d4570dd5-a16b-491b-8958-c81abb1d13bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bdf3ab82-0e7e-4da4-8094-a4e1a195b76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-669a787e0db1007ea4aa7d0e06ce3a23</value>
      <webElementGuid>e866b08d-6634-4960-8a64-a7e8b3065f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'remarks']</value>
      <webElementGuid>65228a6f-7316-42d5-bd98-6dfe73b57ec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'remarks']</value>
      <webElementGuid>9569e843-8d60-414e-8e8f-c236deebd624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'remarks' and @placeholder = 'Describe the non-conformance, what was expected vs. observed, and any actions already taken…' and @id = '_r_3u_-form-item']</value>
      <webElementGuid>12d650fd-910f-4bfc-abc9-833de3dfc9cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
