<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Purchase Order</name>
   <tag></tag>
   <elementGuidId>2b6244a3-3f7c-4492-b95a-9cad1580ca3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Settings&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6901175-83c4-46dc-b786-bc3ac2e869de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>942742b0-92eb-4345-b637-eb9d61768495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex min-w-0 cursor-pointer items-center rounded-[6px] px-2.5 py-1.5 transition-colors duration-100 w-full gap-2.5 bg-[#FEF2F0] text-[#DC291E]</value>
      <webElementGuid>8c6d78aa-1991-466d-84ef-e67b6311fa86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>01d9bb38-2521-474a-aa9f-613e29d0eb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;group/sidebar-wrapper has-data-[variant=inset]:bg-sidebar flex min-h-svh w-full&quot;]/aside[@class=&quot;fixed left-0 bg-white border-r border-[#E5E5E5] flex flex-col overflow-hidden z-50 w-[260px] transition-transform duration-200 ease-out max-md:top-16 max-md:h-[calc(100vh-4rem)] md:top-0 md:h-full max-md:-translate-x-full max-md:pointer-events-none md:translate-x-0 md:pointer-events-auto md:w-[260px]&quot;]/nav[@class=&quot;min-h-0 flex-1 overflow-x-hidden overflow-y-auto px-2 py-1 flex flex-col items-start gap-0.5&quot;]/div[@class=&quot;w-full min-w-0&quot;]/button[@class=&quot;flex min-w-0 cursor-pointer items-center rounded-[6px] px-2.5 py-1.5 transition-colors duration-100 w-full gap-2.5 bg-[#FEF2F0] text-[#DC291E]&quot;]</value>
      <webElementGuid>d75b20f4-7d5a-46b0-9323-3071d40e7125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>9d34fc1b-3d39-4693-93d7-0313106a1669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/aside/nav/div[4]/button</value>
      <webElementGuid>4db4c9d4-b0bc-4968-b05b-47e3467b494c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Task'])[1]/following::button[1]</value>
      <webElementGuid>da59949d-6f1d-42fc-b67f-215a237ce49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders'])[1]/following::button[2]</value>
      <webElementGuid>60a14e6d-9e68-4234-b9b3-90cc9afa9ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Configuration'])[1]/preceding::button[1]</value>
      <webElementGuid>470e462f-3c34-4576-a33d-10e3090b00da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[4]/button</value>
      <webElementGuid>ac471368-89f7-4b85-8ff3-1db700aee910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>ab39f57a-ee61-4bd2-b760-37ff37f45095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
