<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select freight forwarder</name>
   <tag></tag>
   <elementGuidId>9a2d46ca-f403-4d70-97b2-f06ae5ab3e3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#freight_forwarder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='freight_forwarder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aa28dbca-faa3-44c1-ae6c-25df1895fdaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>popover-trigger</value>
      <webElementGuid>5f045391-2af7-4da6-8639-775ac18ebfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center gap-2 whitespace-nowrap transition-[color,box-shadow] cursor-pointer disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg]:shrink-0 ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 focus-visible:ring-4 focus-visible:outline-1 aria-invalid:focus-visible:ring-0 border border-input shadow-xs hover:text-accent-foreground h-9 has-[>svg]:px-3 rounded-sm relative max-md:gap-1 w-full justify-between bg-background font-normal text-active text-sm md:text-lg hover:bg-background my-0 px-[10px] py-[9px] [&amp;_span]:text-sm</value>
      <webElementGuid>501f423d-e0a1-4112-91e4-e135728ce5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>freight_forwarder</value>
      <webElementGuid>032e43f8-9986-4c5b-a7c8-473d1f21f086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>b754ee51-c107-4353-9842-d24d0545c1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b5e9d8d-8caa-47ea-a657-d0f07febbbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>freight_forwarder</value>
      <webElementGuid>e3d08697-89fb-4368-9f44-a3e165509a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>freight_forwarder.components.select-input.trigger</value>
      <webElementGuid>8512e216-ae6b-4769-85fd-7b9bec01f804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7879df4b-4401-4dba-bc37-b28e7aa2bf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>604196e4-3b13-41e9-8a9c-10e4b8b120fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>adcf3799-a78c-4f0c-b2df-c9a2daa64a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select freight forwarder</value>
      <webElementGuid>037c7772-683a-435f-9bca-0ac2f6886370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;freight_forwarder&quot;)</value>
      <webElementGuid>c4104964-4c1b-4c8e-813f-3132e264d559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='freight_forwarder']</value>
      <webElementGuid>8983a54a-c2a3-4b92-a1eb-b3804d1a2ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_3r_']/div/div/div/div/div/div/button</value>
      <webElementGuid>5eeb74ad-6d23-498d-ad9d-943a114ffea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::button[1]</value>
      <webElementGuid>27b9ed05-0222-4612-aa53-28dca8d77c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div/div/button</value>
      <webElementGuid>4e5071ed-cb94-4b7b-87f6-e826b06595ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'freight_forwarder' and @name = 'freight_forwarder' and @type = 'button' and (text() = 'Select freight forwarder' or . = 'Select freight forwarder')]</value>
      <webElementGuid>9d42c744-d984-4007-9781-96f0a2ebfffe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
