<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1D Barcode</name>
   <tag></tag>
   <elementGuidId>abb414e5-e414-4a45-8aa1-ee807c688be6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xs ') and contains(concat(' ', normalize-space(@class), ' '), ' aspect-square ') and (@data-radix-collection-item = '') and (@data-slot = 'radio-group-item') and (@role = 'radio') and (@data-state = 'unchecked')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.text-primary.rounded-full.shadow-xs.aspect-square[data-radix-collection-item=&quot;&quot;][data-slot=&quot;radio-group-item&quot;][role=&quot;radio&quot;][data-state=&quot;unchecked&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f65a9f22-814a-4461-8da9-34e4a8fb51d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9665337e-d9ca-417c-9fb5-2d8ff20dad12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>93e3ba4b-16a7-4d67-8489-80097d243190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c3e32c43-9b93-43ca-b7a1-3417a09c89f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>e439cdcb-973e-4aa4-acc9-b48180f96f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1d_barcode</value>
      <webElementGuid>57943d3f-4aab-42db-bd20-085eb875cced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>radio-group-item</value>
      <webElementGuid>87ccef88-811a-4a89-a9b1-ba7a7936da3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-input text-primary cursor-pointer [data-state=checked]:border [data-state=checked]:border-destructive focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive aspect-square size-4 shrink-0 rounded-full border shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50</value>
      <webElementGuid>f42af578-de73-43e2-968c-aec0d8b54bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>page.freight-warehouse-info.label_code_type.components.radio-field.option-value.1d_barcode</value>
      <webElementGuid>81902c00-4c4b-42eb-a6ae-d64843fe269e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-1d_barcode</value>
      <webElementGuid>b824d9e5-8245-49fa-a62e-9324cefe1cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>466fdac4-a418-49c0-9d58-bdd4169ca1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-632dab3e43c8a874a35ea9baedf096f6</value>
      <webElementGuid>40c60df6-d86c-4675-ba64-398ae9d4c848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xs ') and contains(concat(' ', normalize-space(@class), ' '), ' aspect-square ') and (@data-radix-collection-item = '') and (@data-slot = 'radio-group-item') and (@role = 'radio') and (@data-state = 'unchecked')]</value>
      <webElementGuid>b97ab7a5-d5f6-4447-a377-baad838c442a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xs ') and contains(concat(' ', normalize-space(@class), ' '), ' aspect-square ') and (@data-radix-collection-item = '') and (@data-slot = 'radio-group-item') and (@role = 'radio') and (@data-state = 'unchecked')]</value>
      <webElementGuid>9ea58f35-f4c8-4a04-ae49-0a333835b88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radio-1d_barcode']</value>
      <webElementGuid>ecf99d42-b1e2-4323-ac0a-6de65a518df8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
