<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__r_48</name>
   <tag></tag>
   <elementGuidId>2d445777-a411-4c8e-b66b-2202c7bef767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-ref = 'page.freight-warehouse-info.country.components.select-input.option.Afghanistan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-ref=&quot;page\.freight-warehouse-info\.country\.components\.select-input\.option\.Afghanistan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b136dcdb-a57f-49c8-9477-6605d28dc589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>command-item</value>
      <webElementGuid>510cbb36-642f-4e40-91d3-342709cad838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground [&amp;_svg:not([class*='text-'])]:text-muted-foreground relative flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 cursor-pointer !hover:bg-background hover:font-semibold mb-1</value>
      <webElementGuid>9bd17981-7b2d-461d-98ee-2bcd1ef7bb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>page.freight-warehouse-info.country.components.select-input.option.Afghanistan</value>
      <webElementGuid>06d087d3-1989-45be-8ddb-47cb5798bfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_r_48_</value>
      <webElementGuid>85bb9555-58c4-47b1-b309-1395df90222e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ca31b6af-d467-4d45-9c58-76620fe7ac45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e56e6f5c-cd29-46f1-9e4a-d3f884b77144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8514e646-83c3-4651-9d3c-28f2085b6248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5905db7-efa4-4bec-81e1-e9d17edca3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e10cec1e-e8a7-4f6d-aac8-fc5c85339f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;name&quot;:&quot;Afghanistan&quot;,&quot;isoCode&quot;:&quot;AF&quot;,&quot;flag&quot;:&quot;🇦🇫&quot;,&quot;phonecode&quot;:&quot;93&quot;,&quot;currency&quot;:&quot;AFN&quot;,&quot;latitude&quot;:&quot;33.00000000&quot;,&quot;longitude&quot;:&quot;65.00000000&quot;,&quot;timezones&quot;:[{&quot;zoneName&quot;:&quot;Asia/Kabul&quot;,&quot;gmtOffset&quot;:16200,&quot;gmtOffsetName&quot;:&quot;UTC+04:30&quot;,&quot;abbreviation&quot;:&quot;AFT&quot;,&quot;tzName&quot;:&quot;Afghanistan Time&quot;}]}</value>
      <webElementGuid>5c3a5a90-1f6d-4533-9def-4cdcc9060df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Afghanistan</value>
      <webElementGuid>18707247-8cc6-4d8b-bb6a-f88652e9f5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-417dcfdf793297cf558e910e625d05ea</value>
      <webElementGuid>c70cf7d9-10a7-4d10-a0cb-29cfcac63c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-ref = 'page.freight-warehouse-info.country.components.select-input.option.Afghanistan']</value>
      <webElementGuid>051fcaab-7e62-4f74-ae02-2d9eb1123b2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-ref = 'page.freight-warehouse-info.country.components.select-input.option.Afghanistan']</value>
      <webElementGuid>69973330-b9e9-43e1-a3ef-f27f0ff17744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_r_48_' and (text() = 'Afghanistan' or . = 'Afghanistan')]</value>
      <webElementGuid>00789ebf-978c-4592-971b-a69206d11e0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
