<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__r_73</name>
   <tag></tag>
   <elementGuidId>7db90b12-e8f6-4e9c-b762-0ec7439d0b3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-ref = 'page.freight-warehouse-info.state.components.select-input.option.Badghis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-ref=&quot;page\.freight-warehouse-info\.state\.components\.select-input\.option\.Badghis&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b07a924-e5b7-4e59-8ca5-8686cf728d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>command-item</value>
      <webElementGuid>90b2c707-1424-44a1-8942-662b8349861d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground [&amp;_svg:not([class*='text-'])]:text-muted-foreground relative flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 cursor-pointer !hover:bg-background hover:font-semibold mb-1</value>
      <webElementGuid>ccdff833-96d7-45c9-830b-a15b240123c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>page.freight-warehouse-info.state.components.select-input.option.Badghis</value>
      <webElementGuid>711089ae-5d43-42ae-943d-db92ad0ad7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_r_73_</value>
      <webElementGuid>221d57fb-33a5-420d-9fe2-0b85ad978bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bfbddec3-1171-4d18-95a3-971c65a70ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6e58d52-cbdb-4aa0-90bd-a0dd13835d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6767fa6c-70d5-483d-9134-bbdfc4ae417b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d2927bc7-17fd-4e3e-bb09-b86c39e8a532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0e17ba7f-8027-4cfa-ac15-ce1bb6e5044b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;name&quot;:&quot;Badghis&quot;,&quot;isoCode&quot;:&quot;BDG&quot;,&quot;countryCode&quot;:&quot;AF&quot;,&quot;latitude&quot;:&quot;35.16713390&quot;,&quot;longitude&quot;:&quot;63.76953840&quot;}</value>
      <webElementGuid>4f86be19-0fe9-4d9a-9be1-972804d075f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Badghis</value>
      <webElementGuid>0d017762-f6ce-4292-9aa5-db29de397719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-19fc1236db8ba28c20de85f087e40e32</value>
      <webElementGuid>1389cd40-5fc4-40fb-851b-ae73e608bafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-ref = 'page.freight-warehouse-info.state.components.select-input.option.Badghis']</value>
      <webElementGuid>977c9c94-41cc-4ff2-a79d-154c9dfea293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-ref = 'page.freight-warehouse-info.state.components.select-input.option.Badghis']</value>
      <webElementGuid>6a7087d5-48f7-4ab7-857c-7133e2cf4499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_r_73_' and (text() = 'Badghis' or . = 'Badghis')]</value>
      <webElementGuid>11a884bd-c609-4a63-8fca-3d54ccd4ec0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
