<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__r_88</name>
   <tag></tag>
   <elementGuidId>fe3ba5f3-cb08-4746-95e1-a7386c40373d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-ref = 'page.freight-warehouse-info.city.components.select-input.option.Qala i Naw']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-ref=&quot;page\.freight-warehouse-info\.city\.components\.select-input\.option\.Qala\ i\ Naw&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d4f74f2e-9974-40ad-8bf0-d96bfb4bd848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>command-item</value>
      <webElementGuid>1a464f48-6555-4cca-9ac4-2a850c042d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground [&amp;_svg:not([class*='text-'])]:text-muted-foreground relative flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 cursor-pointer !hover:bg-background hover:font-semibold mb-1</value>
      <webElementGuid>46ece967-046f-4551-bbe5-bf7448926af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>page.freight-warehouse-info.city.components.select-input.option.Qala i Naw</value>
      <webElementGuid>9ded73db-e147-444c-a0e7-eae4c50873af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_r_88_</value>
      <webElementGuid>507c4e7f-35d5-49ec-a897-047871ce467a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>25c64878-f333-4909-80e9-69eaaa277c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ee033a0-7b67-41ca-86cd-765875d0b05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5901d81c-3d97-4f5a-b171-1bc550d7a303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5e83dd27-b0ca-460a-861f-4ed86bf29bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>984f6007-1b5a-46c1-8a30-d2005490ca9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;name&quot;:&quot;Qala i Naw&quot;,&quot;countryCode&quot;:&quot;AF&quot;,&quot;stateCode&quot;:&quot;BDG&quot;,&quot;latitude&quot;:&quot;34.98735000&quot;,&quot;longitude&quot;:&quot;63.12891000&quot;}</value>
      <webElementGuid>1b3edeca-970c-4246-98bb-1053263bc699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qala i Naw</value>
      <webElementGuid>89dea303-459d-432a-ba03-5690aa3e5c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c6c0d973516e7d38790df181d079f3e1</value>
      <webElementGuid>0b2327bf-a2ef-4abf-8ff5-240f63eb8f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-ref = 'page.freight-warehouse-info.city.components.select-input.option.Qala i Naw']</value>
      <webElementGuid>2dfe8314-9da4-449d-8b44-f4de14e88a79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-ref = 'page.freight-warehouse-info.city.components.select-input.option.Qala i Naw']</value>
      <webElementGuid>f45ce701-453e-4b8e-bb86-63c536aa9d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_r_88_' and (text() = 'Qala i Naw' or . = 'Qala i Naw')]</value>
      <webElementGuid>2e25436c-b288-4485-b6ed-5a4687b4a47b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
