<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_At Custom</name>
   <tag></tag>
   <elementGuidId>9b01da81-2e45-476f-a4f5-26ca0e4599b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-_r_5e_-trigger-At Customs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68ec4921-4120-467c-bd2d-84bc38a3ae3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f63e856e-012a-4767-9451-bd6be4f9601a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>415bfce1-a5f4-41b5-ae40-b0a7692d37ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c14d1b7b-51e5-46e1-9e2b-daf589178b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_5e_-content-At Customs</value>
      <webElementGuid>5bdbef9e-635c-40f1-8882-b21b4b715a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>cd6c9027-6a04-44e9-a61c-f726a3d34b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_5e_-trigger-At Customs</value>
      <webElementGuid>733933a8-11a4-44d0-9068-8be591ac0cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>tabs-trigger</value>
      <webElementGuid>3907d53d-abb6-40f5-bb35-884479260989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:outline-ring justify-center whitespace-nowrap focus-visible:ring-[3px] focus-visible:outline-1 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:shadow-sm [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 group flex h-auto cursor-pointer items-center gap-[10px] rounded-none border-0 px-3 py-2.5 text-[14px] font-medium leading-5 text-[#333333] shadow-none transition-colors hover:bg-transparent focus-visible:outline-none data-[state=active]:bg-[#FEF2F0] data-[state=active]:pb-[11px] data-[state=active]:pt-[10px] data-[state=active]:text-[#B10A00] data-[state=active]:border-b data-[state=active]:border-b-[#B10A00]</value>
      <webElementGuid>a8fddc0d-fe5f-41d5-bd0f-c340388eaae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>components.flat-tab.tab-trigger.At Customs</value>
      <webElementGuid>dfc0f326-713d-4fd9-b07d-f48012a3df15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>65f69bee-34bc-4f42-92df-6fc2c6d0757a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>a6bfd36e-56d9-4ae0-ba65-df5a46f2aefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>At Custom0</value>
      <webElementGuid>b1ca2269-4eb8-4264-8b0e-2d61ba01f4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_5e_-trigger-At Customs&quot;)</value>
      <webElementGuid>9cdf15d6-3a01-4f67-afa2-b514ccb7e3ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='radix-_r_5e_-trigger-At Customs']</value>
      <webElementGuid>48aa7b81-0c80-478e-b4c7-532fd7177e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/section/main/div[2]/div/div/div/div/button[9]</value>
      <webElementGuid>da5bea89-3cc3-4d41-9815-e69f0e89641c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Pickup Request'])[1]/following::button[10]</value>
      <webElementGuid>9eee3de9-57ba-43b1-8d34-17e5669438c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk Upload'])[1]/following::button[11]</value>
      <webElementGuid>dd998186-33c7-4320-a166-c9f89ca4dcd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Filter'])[1]/preceding::button[11]</value>
      <webElementGuid>0cea1ff7-9054-4d1c-bcea-5246dc8e1774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Filter'])[2]/preceding::button[13]</value>
      <webElementGuid>9a32fe3c-12eb-431d-8835-dffccad4303d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[9]</value>
      <webElementGuid>79c73845-8ddf-4961-b0bc-87755fedd295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-_r_5e_-trigger-At Customs' and (text() = 'At Custom0' or . = 'At Custom0')]</value>
      <webElementGuid>da90ab66-8718-4e08-98f2-293ba1070118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
