<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Customs Cleared</name>
   <tag></tag>
   <elementGuidId>51b1e7a7-3a1c-4f27-a26b-e2f3b278efb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-_r_5e_-trigger-Customs Cleared']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a163c38a-50fb-4eec-8b5f-9813481744fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b2cf053-c012-4adc-8ff4-bae9031ac8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>75c964f9-04ca-41c2-a83a-d25383b4dd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60f7682e-44ab-45df-aaab-f083c97dba84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_5e_-content-Customs Cleared</value>
      <webElementGuid>ba03ef27-672c-4492-8109-6f1865d676cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>ed59bd08-5e90-4b4f-afb6-03f8b41670a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_5e_-trigger-Customs Cleared</value>
      <webElementGuid>3653f0ba-05e2-41d2-ba99-236698a5e405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>tabs-trigger</value>
      <webElementGuid>68c31dcd-45f1-451f-89c4-acc107cf8676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:outline-ring justify-center whitespace-nowrap focus-visible:ring-[3px] focus-visible:outline-1 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:shadow-sm [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 group flex h-auto cursor-pointer items-center gap-[10px] rounded-none border-0 px-3 py-2.5 text-[14px] font-medium leading-5 text-[#333333] shadow-none transition-colors hover:bg-transparent focus-visible:outline-none data-[state=active]:bg-[#FEF2F0] data-[state=active]:pb-[11px] data-[state=active]:pt-[10px] data-[state=active]:text-[#B10A00] data-[state=active]:border-b data-[state=active]:border-b-[#B10A00]</value>
      <webElementGuid>52d5a7be-beaa-4be2-81c0-819e48cd0905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>components.flat-tab.tab-trigger.Customs Cleared</value>
      <webElementGuid>06bfecb4-a2b2-4a56-bb10-af3aef773ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1938096b-4452-46a2-879c-ece66740ce2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>0e7782d9-13f8-442e-90e6-2ae3e18fe140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customs Cleared1</value>
      <webElementGuid>a6ff82b7-0fcb-484e-af8d-cc855f43d1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_5e_-trigger-Customs Cleared&quot;)</value>
      <webElementGuid>f7d7d4d4-4c87-4262-9ec9-5b60daf73f1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='radix-_r_5e_-trigger-Customs Cleared']</value>
      <webElementGuid>40b7e616-5d8f-4188-858f-d51aec16ad9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/section/main/div[2]/div/div/div/div/button[10]</value>
      <webElementGuid>a41ef9ac-e7c4-4086-8694-3d37ff0c3dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Pickup Request'])[1]/following::button[11]</value>
      <webElementGuid>69bdca90-340e-4ee6-b327-62cba8683f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk Upload'])[1]/following::button[12]</value>
      <webElementGuid>1d0d80e9-09ee-40bf-b307-7ca96351c0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Filter'])[1]/preceding::button[10]</value>
      <webElementGuid>a7bbf525-6a2e-4691-a576-26f8cf32be93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Filter'])[2]/preceding::button[12]</value>
      <webElementGuid>407302b9-5002-4bfc-aaac-e6ab78fb17f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[10]</value>
      <webElementGuid>1d0226e0-e98f-4d95-aa41-551cd2a3c6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-_r_5e_-trigger-Customs Cleared' and (text() = 'Customs Cleared1' or . = 'Customs Cleared1')]</value>
      <webElementGuid>0b272208-bd93-47c6-ace0-752d93f29979</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
