<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sugar Land Pressure Pump  Chem 9035</name>
   <tag></tag>
   <elementGuidId>2549e081-de9f-4220-a20a-55a206812e2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = '6b6d403d-3743-476b-aac0-e6633268e7f1-1-description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;\36 b6d403d-3743-476b-aac0-e6633268e7f1-1-description&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>834758c8-b9f2-4f8a-854f-9f25ea5629e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>213d2456-2845-4c74-a0fd-d2f5f6d28c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>827b2074-13c3-4f15-8885-e20a19d3ac05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0a8c6771-4796-4be6-ae7f-68c67a67a580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>cb81287b-be4b-4717-9195-372ee61e0bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6b6d403d-3743-476b-aac0-e6633268e7f1</value>
      <webElementGuid>12b99b84-ce99-48ce-ba5b-a165c6421aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>radio-group-item</value>
      <webElementGuid>af589ac4-b17c-4e83-b643-7b2405fc007c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-input text-primary cursor-pointer [data-state=checked]:border [data-state=checked]:border-destructive focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive aspect-square size-4 shrink-0 rounded-full border shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 mt-1 after:absolute after:inset-0</value>
      <webElementGuid>f64dae94-d097-4cd6-be10-c3b27dd5d480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6b6d403d-3743-476b-aac0-e6633268e7f1-1</value>
      <webElementGuid>36ba411e-8814-44c4-9bff-2a514f8f0811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>6b6d403d-3743-476b-aac0-e6633268e7f1-1-description</value>
      <webElementGuid>8c9cb55d-6100-4ac4-b80d-5a9c266304b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6af029d0-18a2-4e20-935e-ebc193e7605f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-85d9d01913fde60a8eca7922419c6383</value>
      <webElementGuid>a0469531-876f-48b8-a26e-ca1167c52d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = '6b6d403d-3743-476b-aac0-e6633268e7f1-1-description']</value>
      <webElementGuid>aaab2bc2-1bfc-476d-ae05-dee857d54f3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = '6b6d403d-3743-476b-aac0-e6633268e7f1-1-description']</value>
      <webElementGuid>032f13d2-ced7-47d5-8c4c-dc5593dcb029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '6b6d403d-3743-476b-aac0-e6633268e7f1-1']</value>
      <webElementGuid>39f74582-6c49-4b93-bbe7-31d15cbd4999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
