<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CN002754</name>
   <tag></tag>
   <elementGuidId>0a6fde38-8d5f-4af6-b633-d407441dee3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.bg-\[\#FAFAFA\]:nth-child(2) .underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' bg-[#FAFAFA] ') and (name() = 'tr') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>34381a22-6d6d-4c50-9723-069b9c2808b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline text-blue-5</value>
      <webElementGuid>7f4ecd8c-b750-4d81-a389-81bd445ae4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/console/CN002754/</value>
      <webElementGuid>99612881-c3a6-4df9-9d39-4f79b9b80ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57b1f199-f024-4140-a27f-3929109a95ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CN002754</value>
      <webElementGuid>baf853e1-36cf-462a-a4f7-208ed2696d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-73b5df4c5bdd473759f3f175a57bb45b</value>
      <webElementGuid>e5c21dbd-894e-4cee-861c-f7b5fd4c2c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' bg-[#FAFAFA] ') and (name() = 'tr') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ')]</value>
      <webElementGuid>2b48295b-157a-4991-841b-2f2e07232c2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' bg-[#FAFAFA] ') and (name() = 'tr') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ')]</value>
      <webElementGuid>97a2bc43-224c-42bd-ad1f-8543092f1278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/console/CN002754/' and (text() = 'CN002754' or . = 'CN002754')]</value>
      <webElementGuid>5f59300e-71a3-424c-8c5f-9b73613f3c7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
