<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select freight forwarder</name>
   <tag></tag>
   <elementGuidId>2d892bd3-8283-42bf-bb6a-69c76322acf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='select-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd7aa508-3ea1-404c-9fb6-4c094008d10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>popover-trigger</value>
      <webElementGuid>8b91cf66-2951-499d-b703-cf99336c553e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center gap-2 whitespace-nowrap transition-[color,box-shadow] cursor-pointer disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg]:shrink-0 ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 focus-visible:ring-4 focus-visible:outline-1 aria-invalid:focus-visible:ring-0 border shadow-xs hover:text-accent-foreground py-2 has-[>svg]:px-3 !h-[46px] w-full justify-between bg-background font-medium hover:bg-background my-0 font-red-display h-[46px] rounded-lg border-[#E5E5E5] px-[17px] text-[14px] leading-5 text-[#333]</value>
      <webElementGuid>711d8a97-e012-4087-9392-41ffe6f6dc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>820997b0-801f-40ce-b766-053f626458e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>30c94b52-dc51-4ce2-bc3f-94d917f62475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3ab3e79-36f6-4fea-b59b-dc035c7c22a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>components.select-input.trigger</value>
      <webElementGuid>563e4d7f-03bd-40d6-bbae-47ba9c740c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3523fffd-030b-4ae7-9f2f-b5b4dad203b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>0caf170e-efa4-4fb6-aa17-d5874deb9824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_27_</value>
      <webElementGuid>62c89cb4-7478-406d-be06-169fe7f1ac88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>69baf933-5e52-40e3-85e6-4ab7b9c9258c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select freight forwarder</value>
      <webElementGuid>a8c02a85-5717-4fed-9528-707da23ba838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_26_&quot;)/div[@class=&quot;border-t border-[#EBEBEB] px-4 pb-4 pt-[5px]&quot;]/div[@class=&quot;flex flex-col gap-4 pt-3&quot;]/div[@class=&quot;grid gap-4 grid-cols-1 sm:grid-cols-2&quot;]/div[@class=&quot;flex flex-col gap-[6px]&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;rounded-sm&quot;]/button[@id=&quot;select-input&quot;]</value>
      <webElementGuid>ef31a028-eddf-4934-9990-8f3b813d01a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='select-input']</value>
      <webElementGuid>db04ae62-7f38-46e3-b030-07fa1a3b8852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_26_']/div/div/div/div/div/div/button</value>
      <webElementGuid>2d820563-58a0-4a49-af40-1bc588979e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::button[1]</value>
      <webElementGuid>a983d7f2-0c52-4b54-81ea-e38b24077adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div/div/button</value>
      <webElementGuid>2a8de030-67a7-4e81-a214-d57703105676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'select-input' and @type = 'button' and (text() = 'Select freight forwarder' or . = 'Select freight forwarder')]</value>
      <webElementGuid>9b88315a-6543-46da-a233-7591eb48df66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
