<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_select-input</name>
   <tag></tag>
   <elementGuidId>e6a3fe17-f749-4703-9e5c-4dacf3cbcb11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.grid:nth-child(1) #select-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' grid ') and (name() = 'div') and (position() = 1)]//*[@id = 'select-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>942384e6-5e5c-42b4-b55d-12de9497a4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>popover-trigger</value>
      <webElementGuid>d40d99a2-b580-40af-8d22-f79fa621e00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center gap-2 whitespace-nowrap transition-[color,box-shadow] cursor-pointer disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg]:shrink-0 ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 focus-visible:ring-4 focus-visible:outline-1 aria-invalid:focus-visible:ring-0 border shadow-xs hover:text-accent-foreground py-2 has-[>svg]:px-3 !h-[46px] w-full justify-between bg-background font-medium hover:bg-background my-0 font-red-display h-[46px] rounded-lg border-[#E5E5E5] px-[17px] text-[14px] leading-5 text-[#333]</value>
      <webElementGuid>d679db38-ab8c-4c3e-ba4f-a7e5eea29bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-input</value>
      <webElementGuid>c5221a8f-2261-4dbb-a1fa-df74f45a4093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>fa4ba133-9d04-4f2f-9b32-e4ad5fd4ed60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f1778785-a977-43a7-8cb5-92520584a51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>components.select-input.trigger</value>
      <webElementGuid>2ad3b655-bf6c-421d-b8e7-d22855786579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>187b574f-ea51-4c6f-b281-eed1348e55fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>275a8f53-ca46-4840-8db9-a693530becce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_27_</value>
      <webElementGuid>38a95821-c6d7-43dd-b10f-e85ae7db346e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>361f5cf6-ade1-486d-970d-ee8066bb6b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select freight forwarder</value>
      <webElementGuid>f951f460-4a72-4533-b0ac-1be8e13540b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5e830d7d80dc7a5ea9247a9577abbc8f</value>
      <webElementGuid>eec8d9cf-cd8a-4afd-8243-8f26da6b9ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' grid ') and (name() = 'div') and (position() = 1)]//*[@id = 'select-input']</value>
      <webElementGuid>a02619ca-330c-4101-b64f-7a496e69746f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' grid ') and (name() = 'div') and (position() = 1)]//*[@id = 'select-input']</value>
      <webElementGuid>2df6bc25-b338-462b-9cbb-72b350c53a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'select-input' and @type = 'button' and (text() = 'Select freight forwarder' or . = 'Select freight forwarder')]</value>
      <webElementGuid>8eea0d93-09a8-4f53-ac97-5d3f14c8d2d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
