<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__r_32</name>
   <tag></tag>
   <elementGuidId>6ddd5c09-cabb-41ce-b36b-38d3cf8cd324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-ref=&quot;components\.select-input\.option\.Fasttrac\ \(RAOD\)&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-ref = 'components.select-input.option.Fasttrac (RAOD)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bfe00df1-5085-47ce-8b22-d2421671b95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>command-item</value>
      <webElementGuid>cc3282db-1d23-4ce2-a0d8-b54185bd2bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground [&amp;_svg:not([class*='text-'])]:text-muted-foreground relative flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 cursor-pointer !hover:bg-background hover:font-semibold mb-1</value>
      <webElementGuid>3bd72757-0416-459e-b592-6642b9d69b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>components.select-input.option.Fasttrac (RAOD)</value>
      <webElementGuid>6bd073cf-8037-49f7-b335-c82147be0c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_r_32_</value>
      <webElementGuid>8fe3d864-2e22-4ad5-bd79-2fcee593d990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>72f283b0-7f2f-4833-83c2-165396084a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3c22df4-30d3-4da8-b24a-e146bc535e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef4330bf-bca8-4029-8348-266d62a5ad2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec59aa49-9354-437c-adc8-6633e9392a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d46f2a7-666a-4e05-b0de-39cea90e6535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;c953786e-1ae4-43ee-89f2-beba72d7dd60&quot;,&quot;name&quot;:&quot;Fasttrac&quot;,&quot;mot&quot;:&quot;f2bbf69c-bde2-4558-b265-e831792c7612&quot;,&quot;mot__mot_type&quot;:&quot;RAOD&quot;,&quot;mc_dot&quot;:&quot;MC #379737&quot;,&quot;scac&quot;:&quot;Fasttrac&quot;,&quot;tracking_number_prefix&quot;:&quot;FASTRAC123456&quot;,&quot;is_active&quot;:true}</value>
      <webElementGuid>af5fd12a-0bc7-4b90-bbfd-0acc20b6f80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fasttrac (RAOD)</value>
      <webElementGuid>67031064-f3b0-4126-9a5b-92e993a9ac7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bd0774ed51606198675a94d924072672</value>
      <webElementGuid>3bd10a80-c1b3-4461-b18d-74805b2f90de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-ref = 'components.select-input.option.Fasttrac (RAOD)']</value>
      <webElementGuid>4658bc29-4083-472c-b0d3-5cbed2803a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-ref = 'components.select-input.option.Fasttrac (RAOD)']</value>
      <webElementGuid>dc80af60-1df2-46f9-bc22-ba3b99caace6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_r_32_' and (text() = 'Fasttrac (RAOD)' or . = 'Fasttrac (RAOD)')]</value>
      <webElementGuid>7ca4b1c0-03b4-46a0-b8a3-8713bd93f349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
