<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CN002751</name>
   <tag></tag>
   <elementGuidId>510d5750-514e-4d60-8df5-cbeb121588aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.group:nth-child(1) .underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' group ') and (name() = 'tr') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b88444b-8894-40b7-aa9b-bfc2651b2f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline text-blue-5 cursor-pointer</value>
      <webElementGuid>5dd63d1a-583f-4e82-a896-f9c51d3c98de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consignment/create-v2/?currentStep=4&amp;view=true</value>
      <webElementGuid>77912a41-33bd-49d3-9cf4-e4840e7da70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32dd516f-63c7-4191-83d4-5cda47df3c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PKU04211</value>
      <webElementGuid>7c956667-3db8-4aca-ad83-dbc6a52a5a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-beea4c349e144a58299e0a295b27fb67</value>
      <webElementGuid>5cb82746-9316-4d28-951d-3c2dfd0f1382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' group ') and (name() = 'tr') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ')]</value>
      <webElementGuid>5b35cf4d-f535-4e70-9d4e-d0f8a91887e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' group ') and (name() = 'tr') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ')]</value>
      <webElementGuid>4777f71c-f667-4288-97fa-7e5be64a244e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/consignment/create-v2/?currentStep=4&amp;view=true' and (text() = 'PKU04211' or . = 'PKU04211')]</value>
      <webElementGuid>8fd76646-4af6-466a-95df-024912ebf62b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
