<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_checkbox_1</name>
   <tag></tag>
   <elementGuidId>a8b747f8-73f3-4315-b160-8904306026e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.font-light.bg-white.text-center .peer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-light ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-white ') and contains(concat(' ', normalize-space(@class), ' '), ' text-center ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0c752c6-c630-4933-8d4e-1156db644bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c136051-611d-4d0c-b62a-d26aa026b853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c1256dff-d86f-45ee-b68b-47eb4e103ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>73336fc6-6f16-44f1-82d8-db0bc06c01c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>a543cf7a-c8d7-4b70-b0a7-bfc050321bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8b671bfe-7fa9-4502-8abc-9bfe222cfee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4a642876-4c6f-447e-9709-bc50ec7fb236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer peer border-input data-[state=unchecked]:bg-white data-[state=checked]:bg-primary data-[state=indeterminate]:bg-primary data-[state=checked]:text-primary-foreground data-[state=checked]:border-primary data-[state=indeterminate]:border-primary focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive size-4 shrink-0 rounded-[4px] border shadow-xs transition-shadow outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50</value>
      <webElementGuid>8bf0fbfd-f34e-4aae-a347-576bdd746e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fda1ab1f0d50748a4c2caef160c75dd3</value>
      <webElementGuid>296490f7-cd03-4a1f-98d1-3e798a10c26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-light ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-white ') and contains(concat(' ', normalize-space(@class), ' '), ' text-center ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ')]</value>
      <webElementGuid>2b330537-18a3-48ad-8e77-f1311baace2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-light ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-white ') and contains(concat(' ', normalize-space(@class), ' '), ' text-center ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' peer ')]</value>
      <webElementGuid>2e9edda9-ce97-40ce-b73e-ba14d21e706f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>d4bc1eae-7a67-48d1-b17c-060ca4d83ba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
