<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pickup</name>
   <tag></tag>
   <elementGuidId>f1086530-8792-46ff-94fd-e285454d19a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;Pickup&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = 'Pickup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>710b0646-6f3c-42f6-906d-7abc8d3e031a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1658ec2-8745-426f-a1d6-a54514501490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex min-w-0 cursor-pointer items-center rounded-[6px] px-2.5 py-1.5 transition-colors duration-100 mx-auto w-10 h-10 justify-center text-[#333333] hover:bg-gray-50</value>
      <webElementGuid>530bf553-2a8f-4a83-81d1-78db9a79e807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pickup</value>
      <webElementGuid>97cfb644-2790-4e6d-b735-d3cab193c758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1be91ee6a9387bf95c750461dd71f5ac</value>
      <webElementGuid>228e5166-131b-4cbf-977f-a90c06412c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = 'Pickup']</value>
      <webElementGuid>3b5d31fe-ad62-4fe5-9f37-5560d72bf82a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = 'Pickup']</value>
      <webElementGuid>80e114f2-7580-4429-a716-5bbbcabae1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Pickup']</value>
      <webElementGuid>9e5d8d02-559b-4057-ab10-74279cff26fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
