<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Downloads</name>
   <tag></tag>
   <elementGuidId>915e5ad1-ed07-4a85-823b-0485b6413783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;Downloads&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = 'Downloads']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>156ce4e9-f68a-44ba-b37a-677e63795787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85457495-fd0c-4d04-9bce-8f50a264af70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex min-w-0 cursor-pointer items-center rounded-[6px] px-2.5 py-1.5 transition-colors duration-100 mx-auto w-10 h-10 justify-center text-[#333333] hover:bg-gray-50</value>
      <webElementGuid>8fc2c056-0d96-4629-852d-b53537f4ea24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Downloads</value>
      <webElementGuid>0120fa55-1d7e-4ae7-b202-a94cb3b8c837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f06f79bf8f69f69dd01b6246364f83c9</value>
      <webElementGuid>42e526c1-1ea2-4e14-b625-50468560c437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = 'Downloads']</value>
      <webElementGuid>3bb961ed-c81c-4e82-8532-d6865f5d7329</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = 'Downloads']</value>
      <webElementGuid>867b19a8-dfb0-4a37-818b-ff4ac79f9464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Downloads']</value>
      <webElementGuid>67a19ac9-3de4-458f-8351-8cdd65902c74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
