<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_cursor-pointer</name>
   <tag></tag>
   <elementGuidId>ada44a21-8e7a-4bd3-871a-11e4cec8e9af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.cursor-pointer[fill=&quot;none&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//svg[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (@fill = 'none')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f26d305b-cd09-4b7a-9d34-39ba7828a87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>ca2522f0-66f6-4f25-ad08-118bce2159a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>b4984aa2-4762-49d5-9c6d-c786b28bdbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>49d5d194-55c5-4379-9cbc-a3a9c34ba4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>859dd791-c28b-4d02-8de6-0e99a851a8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>0d998691-7025-4f16-b5fc-882fabb5d892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>36fbf16f-c566-4db1-a831-6ae47bc8d723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4ace861bae5f28af6d8af51849ba7341</value>
      <webElementGuid>c213954b-f29e-44e5-9e9d-f4f4fc686332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//svg[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (@fill = 'none')]</value>
      <webElementGuid>1cf075d6-c9a4-4ce9-a2da-c9bbc320f52e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//svg[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (@fill = 'none')]</value>
      <webElementGuid>9ff80236-3507-451d-9150-fd54731830a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
